### ISSUE TITLE
docker-compose  创建 zk 集群

### ISSUE THREAD

**Issue by ShuoWu3000** [smiecj/docker-centos#11]
使用docker-compose创建集群，java通过Curator无法连接，报错如下
```java
2022-09-09 14:38:34.746 [main-EventThread] INFO  org.apache.curator.framework.imps.EnsembleTracker Line:201 - New config event received: {server.1=0.0.0.0:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zk3:2888:3888:participant;0.0.0.0:2181, server.2=zk2:2888:3888:participant;0.0.0.0:2181}
2022-09-09 14:38:34.776 [main] INFO  com.zaxxer.hikari.HikariDataSource Line:123 - HikariPool-1 - Start completed.
2022-09-09 14:38:34.794 [main-EventThread] INFO  org.apache.curator.utils.Compatibility Line:47  - Using org.apache.zookeeper.server.quorum.MultipleAddresses
2022-09-09 14:38:34.798 [main-EventThread] ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl Line:733 - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116)
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:926)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:683)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:644)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:563)
2022-09-09 14:38:34.802 [main-EventThread] INFO  org.apache.curator.framework.imps.EnsembleTracker Line:201 - New config event received: {server.1=0.0.0.0:2888:3888:participant;0.0.0.0:2181, version=0, server.3=zk3:2888:3888:participant;0.0.0.0:2181, server.2=zk2:2888:3888:participant;0.0.0.0:2181}
2022-09-09 14:38:34.803 [main-EventThread] ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl Line:733 - Background exception was not retry-able or retry gave up
java.lang.NullPointerException: null
        at org.apache.curator.utils.Compatibility.getHostAddress(Compatibility.java:116)
        at org.apache.curator.framework.imps.EnsembleTracker.configToConnectionString(EnsembleTracker.java:185)
        at org.apache.curator.framework.imps.EnsembleTracker.processConfigData(EnsembleTracker.java:206)
        at org.apache.curator.framework.imps.EnsembleTracker.access$300(EnsembleTracker.java:50)
        at org.apache.curator.framework.imps.EnsembleTracker$2.processResult(EnsembleTracker.java:150)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:926)
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:683)
        at org.apache.curator.framework.imps.WatcherRemovalFacade.processBackgroundOperation(WatcherRemovalFacade.java:152)
        at org.apache.curator.framework.imps.GetConfigBuilderImpl$2.processResult(GetConfigBuilderImpl.java:222)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:644)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:563)
```

**Comment by smiecj** [comment]
我在本地通过 REPO=mzsmieli make run_zookeeper_cluster 可以正常运行，并且通过 connectString=zookeeper1:2181 也能正常连接。可以先确定下你的启动方式是否一致
